# mkdocs.yml
site_name: nestedutils
site_description: The lightweight Python library for safe, simple, dot-notation access to nested dicts and lists. Effortlessly get, set, and delete values deep in your complex JSON, API responses, and config files without verbose error-checking or handling KeyError exceptions.
site_author: Y. Siva Sai Krishna
site_url: "https://ysskrishna.github.io/nestedutils"
repo_name: "ysskrishna/nestedutils"
repo_url: "https://github.com/ysskrishna/nestedutils"
copyright: Copyright &copy; 2025 Y. Siva Sai Krishna
docs_dir: docs


nav:
  - Project Readme: PROJECT-README.md
  - API Reference: index.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            docstring_style: google
            merge_init_into_class: true
theme:
  name: material
  locale: en
  features:
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: .

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nestedutils/

    - icon: fontawesome/solid/external-link
      link: https://ysskrishna.vercel.app
    - icon: fontawesome/brands/github
      link: https://github.com/ysskrishna
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ysskrishna
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/ysskrishna