# mkdocs.yml
site_name: nestedutils
site_description: The lightweight Python library for safe, simple, dot-notation access to nested dicts and lists. Effortlessly get, set, and delete values deep in your complex JSON, API responses, and config files without verbose error-checking or handling KeyError exceptions.
site_author: Y. Siva Sai Krishna
site_url: "https://ysskrishna.github.io/nestedutils"
repo_name: "ysskrishna/nestedutils"
repo_url: "https://github.com/ysskrishna/nestedutils"
copyright: Copyright &copy; 2025 Y. Siva Sai Krishna
docs_dir: docs


nav:
  - Home: index.md
  - API Reference: api-reference.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            docstring_style: google
            merge_init_into_class: true
theme:
  name: material
  custom_dir: docs/theme/overrides
  locale: en
  features:
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: .

extra:
  google_site_verification: "ICfb1XMVpLJZcn7JdUoaUsNZ-0D8LH1uztDuFd0VNfM"
  og_image: https://raw.githubusercontent.com/ysskrishna/nestedutils/main/media/og.png
  keywords:
    - nested
    - nested-data
    - nested-dict
    - json-access
    - json-utils
    - dot-notation
    - dot-access
    - path-access
    - keypath
    - deep-get
    - deep-set
    - deep-access
    - deep-delete
    - safe-access
    - KeyError
    - no-keyerror
    - key-error-handling
    - dictionary
    - dict
    - list
    - json
    - config
    - dict-utils
    - data-utils
    - config-utils
    - utilities
    - utils
    - open source
    - API reference
    - contribution guide
    - changelog
    - version history
    - MIT license
    - ysskrishna
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nestedutils/
    - icon: fontawesome/solid/external-link
      link: https://ysskrishna.vercel.app
    - icon: fontawesome/brands/github
      link: https://github.com/ysskrishna
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ysskrishna
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/ysskrishna