# mkdocs.yml
site_name: nestedutils
site_description: The lightweight Python library for safe, simple, dot-notation access to nested dicts and lists. Effortlessly get, set, and delete values deep in your complex JSON, API responses, and config files without verbose error-checking or handling KeyError exceptions.
site_author: Y. Siva Sai Krishna
site_url: "https://pypi.org/project/nestedutils"
repo_url: "https://github.com/ysskrishna/nestedutils"
copyright: Copyright &copy; 2025 Y. Siva Sai Krishna
docs_dir: .
site_dir: ../site


nav:
  - Project Readme: README.md
  - API Reference: docs/index.md
  - Development: DEVELOPMENT.md
  - Changelog: CHANGELOG.md

plugins:
  - search
  - same-dir
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            docstring_style: google
            merge_init_into_class: true
theme:
  name: readthedocs
  locale: en

markdown_extensions:
  - admonition
  - toc:
      permalink: true